version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    vars:
      NESTED_MODULES: api
      API_DIRS: '{{.ROOT_DIR}}/api/...'
      MANIFEST_OUT: '{{.ROOT_DIR}}/api/crds/manifests'
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/...'
      COMPONENTS: 'cluster-provider-gardener'
      REPO_URL: 'https://github.com/openmcp-project/cluster-provider-gardener'
      CHART_COMPONENTS: "[]"
      GENERATE_DOCS_INDEX: "true"
      CRDS_COMPONENTS: 'cluster-provider-gardener'
      CRDS_PATH: '{{.ROOT_DIR}}/api/crds/manifests'
