package v1alpha1

import (
	gardenv1beta1 "github.com/openmcp-project/cluster-provider-gardener/api/external/gardener/pkg/apis/core/v1beta1"
)

type ClusterStatus struct {
	// Shoot contains the shoot manifest generated by the controller.
	// +optional
	Shoot *gardenv1beta1.ShootTemplate `json:"shoot,omitempty"`
}
